steps:
  mtaBuild:
    platform: 'CF'
    
  cloudFoundryDeploy:
    cfOrg: "bf600639trial"
    cfSpace: 'dev'
    cfApiEndpoint: https://api.cf.us10.hana.ondemand.com
    cfCredentialsId: 'CF_CREDENTIALSID'
